name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: c-hive/gha-yarn-cache@v2

    - name: Install JS dependencies
      run: yarn install
    - name: Test
      run: yarn lint
